### ISSUE TITLE
Any update on this?

### ISSUE THREAD

**Issue by solomongifford** [marklee77/ansible-role-pwm#1]
Thanks.

**Comment by marklee77** [comment]
I wound up creating a different solution using the ldap toolbox self-service password web interface (https://github.com/marklee77/ansible-role-ltb-self-service-password).

pwm has more features, but it's a bit harder to script the deployment.

**Comment by solomongifford** [comment]
Thanks- I was able to get it working for us except that I can't figure out how to generate the LDAP Proxy Password. Guess I'll have to read some pwm code;)

**Comment by solomongifford** [comment]
Just in case anyone comes accross this, I solved the LDAP Proxy Password generation issue with:

<pre>
import password.pwm.util.Helper;
import password.pwm.PwmConstants;
import javax.crypto.SecretKey;
import java.security.NoSuchAlgorithmException;
import java.io.UnsupportedEncodingException;
import password.pwm.error.PwmUnrecoverableException;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
class PasswordGenerator {
    public static void main(String[] args) throws NoSuchAlgorithmException, UnsupportedEncodingException, PwmUnrecoverableException, ParseException {
        String target = args[1];
        DateFormat df = new SimpleDateFormat("EEE MMM dd kk:mm:ss z yyyy");
        String key = PwmConstants.DEFAULT_DATETIME_FORMAT.format(df.parse(target)) + "StoredConfiguration";
        SecretKey secretKey = Helper.SimpleTextCrypto.makeKey(key);
        String encodedValue = Helper.SimpleTextCrypto.encryptValue(args[0], secretKey);
        System.out.println(encodedValue);
    }
}
</pre>

Now, if the date in the config is 2015-02-13 17:26:40 +0000, then argument two for the script above is Fri Feb 13 12:26:40 EST 2015. First argument is the password to convert.
